id: I8D129FD0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:47:59+00:00'
last_modified: '2022-06-08T03:44:52.599574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19202
  title: བཀའ་བརྒྱུད་པའི་ཞལ་འདོན།
  author: ''
  base:
    A454:
      image_group_id: I2PD19217
      title: ''
      total_pages: 304
      order: 1
      base_file: A454.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
